<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="0" name="Failure" package="" tests="1">
    <testcase classname="Failure" name="fail">
      <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: 
	at Failure.fail(Unknown Source)
</failure>
    </testcase>
    <properties>
      <property name="ant.project.invoked-targets" value="test" />
    </properties>
    <system-out />
    <system-err />
  </testsuite>
  <testsuite errors="0" failures="0" name="Error" package="" tests="1">
    <testcase classname="Error" name="error">
      <error type="java.lang.Error">java.lang.Error
	at Error.error(Unknown Source)
</error>
    </testcase>
    <properties>
      <property name="ant.project.invoked-targets" value="test" />
    </properties>
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
